baseURL = "https://pendidikan360.my/"
languageCode = "ms-MY"
title = "Pendidikan360"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[params]
  env = "production"
  title = "Pendidikan360"
  description = "Sumber rujukan pendidikan Malaysia untuk guru, pensyarah dan pendidik merangkumi Pembelajaran Bermakna, Pentaksiran, Pembelajaran Digital, Teknologi Pendidikan dan AI dalam Pendidikan."
  author = "Pendidikan360"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
  Title = "Dunia Pendidikan. Global dan Lokal. 🎓"
  Content = "Sumber rujukan pendidikan Malaysia untuk guru, pensyarah dan pendidik merangkumi Pembelajaran Bermakna, Pentaksiran, Pembelajaran Digital, Teknologi Pendidikan dan AI dalam Pendidikan."

[[params.socialIcons]]
  name = "email"
  url = "mailto:admin@pendidikan360.my"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
    identifier = "sejarah"
    name = "Sejarah"
    url = "/categories/sejarah-pendidikan/"
    weight = 10

  [[menu.main]]
    identifier = "falsafah"
    name = "falsafah"
    url = "/categories/falsafah/"
    weight = 20

[[menu.main]]
    identifier = "psikologi"
    name = "psikologi"
    url = "/categories/psikologi/"
    weight = 30

[[menu.main]]
    identifier = "sosiologi"
    name = "sosiologi"
    url = "/categories/sosiologi/"
    weight = 40

[[menu.main]]
    identifier = "pembelajaran"
    name = "pembelajaran"
    url = "/categories/pembelajaran/"
    weight = 50

[[menu.main]]
    identifier = "pedagogi"
    name = "pedagogi"
    url = "/categories/pedagogi/"
    weight = 60

[[menu.main]]
    identifier = "pentaksiran"
    name = "pentaksiran"
    url = "/categories/pentaksiran/"
    weight = 70

[[menu.main]]
    identifier = "penyelidikan"
    name = "penyelidikan"
    url = "/categories/penyelidikan/"
    weight = 80

[[menu.main]]
    identifier = "teknologi"
    name = "teknologi"
    url = "/categories/teknologi-pendidikan/"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "Cari"
    url = "/search/"
    weight = 99

[outputs]
  home = ["HTML", "RSS", "JSON"]